import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { StoreProvider } from "@/redux/StoreProvider";
import TopBar from "@/component/TopBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Movie Hunt",
  description: "Generated by Mohamad Osman Goni",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <TopBar/>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
