import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { StoreProvider } from "@/redux/StoreProvider";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="flex justify-between items-center max-w-[1200px] mx-auto mt-10 mb-0">
            <button className="cursor-pointer border-2 p-2 border-gray-600 rounded-md hover:bg-[#262F40] hover:text-white text-md">
              <Link href={"/"}> Popular Movie</Link>
             </button>
             <button className="cursor-pointer border-2 p-2 border-gray-600 rounded-md hover:bg-[#262F40] hover:text-white text-md">
              <Link href={"/watchlist"}> WatchList Movie</Link>
             </button>
          </div>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
